-- Reference: apply on STAGING in order (Supabase SQL Editor or CLI).
-- Do not run blindly on production without backup.
-- Full runbook: docs/MIGRATION_RUNBOOK.md

-- 0026_kyc_wizard_residence.sql
-- 0027_landlord_verification_wizard.sql
-- 0028_market_intelligence_pilot_webhooks.sql
-- 0029_webhook_delivery_retries.sql
-- 0030_landlord_licensable_notify.sql
-- 0031_market_capture_suburb_snapshot.sql
-- 0032_notification_market_alerts.sql
-- 0033_two_factor_totp.sql
-- 0034_payment_eft_proofs.sql
-- 0035_notifications_realtime.sql
-- 0036_phase1_trust.sql
-- 0037_phase2_growth.sql
-- 0038_phase2_dispute_appeals.sql
-- 0039_email_delivery_reliability.sql
-- 0040_fraud_detection.sql
-- 0041_score_narrative.sql
-- 0042_score_history_metadata.sql
-- 0043_phase3_b2b_demo_dataset.sql
-- 0044_phase2_tail.sql
-- 0045_sms_2fa.sql

-- After apply, verify:
--   SELECT column_name FROM information_schema.columns
--   WHERE table_schema = 'public' AND table_name = 'profiles'
--     AND column_name IN ('partner_approval_status', 'two_factor_verified_until');
--   SELECT column_name FROM information_schema.columns
--   WHERE table_schema = 'public' AND table_name = 'payments'
--     AND column_name IN ('auto_confirm_at', 'confirmed_via', 'confirmation_disputed_at');

-- RLS policies live in migration 0012_rls_policies.sql (re-apply safe via CREATE OR REPLACE policies there).
